---
title: Jonathan Braga
email: jonathanb2br@gmail.com
description: 'Co-Founder @iFabric | Xamarin Developer| Web Developer

'
baseurl: ''
url: ''
twitter_username: __jonathan_
github_username: jonathanbraga
markdown: kramdown
theme: minima
gems: 
- jekyll-gist
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
